<a href="https://colab.research.google.com/github/Harshita991/college/blob/master/basic_numpy_qus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [6]:
mylist = [1,2,3,4]
print(mylist)

[1, 2, 3, 4]


In [11]:
a = np.array([[1.],[10.5],[2.5]],dtype=float)
print(type(a))
print(a)
print(a)

[[ 1  2  3]
 [10 37 45]
 [ 2  3  8]]


In [16]:
a = np.array([[1.],[10.5],[2.5]],dtype=float)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[ 1. ]
 [10.5]
 [ 2.5]]


In [19]:
a = np.array([[1.],[10.5],[2.5]],dtype=float)
b = np.array([[1,2,4,],[10,5,5],[2,4,5]])
print(type(a))
print(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[ 1. ]
 [10.5]
 [ 2.5]]
<class 'numpy.ndarray'>
[[ 1  2  4]
 [10  5  5]
 [ 2  4  5]]


In [23]:
# np. array
b = np.arange(100,777)
print(b)


[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279
 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297
 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315
 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333
 334 335 336 337 338 339 340 341 342 343 344 345 34

In [40]:
b = np.arange(10).reshape(2,5)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [43]:
b = np.arange(24).reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [54]:
b = np.arange(48).reshape(6,8,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]]

 [[24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]
  [31]]

 [[32]
  [33]
  [34]
  [35]
  [36]
  [37]
  [38]
  [39]]

 [[40]
  [41]
  [42]
  [43]
  [44]
  [45]
  [46]
  [47]]]
